export const STRINGS = {
  common: {
    confirmed: 'Đã xác nhận',
    pending: 'Đang chờ',
    cancelled: 'Đã hủy',
    loading: 'Đang tải...',
    error: 'Đã có lỗi xảy ra',
    retry: 'Thử lại',
    close: 'Đóng',
    back: 'Quay lại',
    save: 'Lưu',
    edit: 'Sửa',
    delete: 'Xóa',
    confirm: 'Xác nhận',
    share: 'Chia sẻ',
    later: 'Để sau',
    login: 'Đăng nhập',
    got_it: 'Đã hiểu',
    great: 'Tuyệt vời',
    stay: 'Ở lại',
    keep: 'Giữ lại',
  },
  session: {
    status: {
      open: 'Đang mở',
      full: 'Đã đầy',
      starting_soon: 'Sắp bắt đầu',
      past: 'Đã kết thúc',
      cancelled: 'Đã hủy',
      in_progress: 'Đang diễn ra',
    },
    booking: {
      confirmed: 'Đã đặt sân',
      unconfirmed: 'Chưa đặt sân',
      waiting: 'Chờ đặt sân',
    },
    roles: {
      host: 'Chủ kèo',
      player: 'Thành viên',
    },
    actions: {
      join: 'Vào kèo',
      leave: 'Rời kèo',
      cancel_request: 'Hủy yêu cầu',
      review_requests: 'Duyệt yêu cầu',
      edit_session: 'Sửa kèo',
      report_result: 'Báo kết quả',
      confirm_result: 'Xác nhận kết quả',
    },
  },
  home: {
    greeting: {
      morning: 'Chào buổi sáng',
      afternoon: 'Chào buổi chiều',
      evening: 'Chào buổi tối',
      default: 'Xin chào',
    },
    prompts: {
      ready: 'Đã sẵn sàng ra sân chưa?',
      join_today: 'Hôm nay ra sân chứ?',
    },
    sections: {
      streak: 'CHUỖI RA SÂN',
      personalized: 'Dành riêng cho bạn',
      personalized_sub: 'Gợi ý hợp gu',
      rescue: 'Cứu nét khẩn cấp',
      rescue_sub: 'Cần người gấp',
      familiar_courts: 'Sân ở gần bạn',
      familiar_courts_sub: 'Sân ở gần',
      upcoming: 'Trận của bạn',
      upcoming_sub: 'Sắp diễn ra',
    },
    actions: {
      create_session: 'Tạo kèo mới',
      view_session: 'XEM KÈO',
      join_session: 'VÀO KÈO',
      prioritize_match: 'ƯU TIÊN GHÉP',
      ready: 'Sẵn sàng',
    },
  },
  find_session: {
    title: 'TÌM KÈO',
    search_placeholder: 'Tìm theo tên sân, địa chỉ...',
    filters: {
      title: 'Bộ lọc',
      skill_level: 'Trình độ',
      date: 'Ngày chơi',
      court: 'Sân đấu',
      reset: 'Thiết lập lại',
      apply: 'Áp dụng',
    },
    empty: {
      no_results: 'Không tìm thấy kèo nào',
      no_results_sub: 'Thử thay đổi bộ lọc hoặc khu vực tìm kiếm khác xem sao nhé.',
    },
  },
  profile: {
    title: 'HỒ SƠ',
    edit_title: 'SỬA HỒ SƠ',
    sections: {
      info: 'THÔNG TIN',
      skill: 'TRÌNH ĐỘ',
      connection: 'KHỚP KÈO NHANH',
      overview: 'TỔNG QUAN',
      community: 'CỘNG ĐỒNG',
      achievements: 'DANH HIỆU',
      courts: 'SÂN QUEN',
      history: 'LỊCH SỬ',
      account: 'TÀI KHOẢN',
      settings: 'CÀI ĐẶT',
    },
    fields: {
      name: 'Tên',
      bio: 'Giới thiệu',
      city: 'Thành phố',
      auto_accept: 'Tự động nhận kèo phù hợp',
    },
    placeholders: {
      bio: 'Viết vài dòng về bạn...',
    },
    stats: {
      matches: 'Trận đấu',
      hosted: 'Đã host',
      reliability: 'Độ tin cậy',
      joined_year: 'Thành viên từ',
    },
    actions: {
      edit: 'Sửa hồ sơ',
      logout: 'Đăng xuất',
      redo_assessment: 'Làm lại đánh giá',
      save: 'Lưu thay đổi',
      cancel: 'Hủy thay đổi',
      save_changes: 'Lưu thay đổi',
      cancel_changes: 'Hủy thay đổi',
    },
    status: {
      saved: 'Đã lưu',
    },
    errors: {
      max_courts: 'Đã đạt giới hạn sân yêu thích',
    },
    empty: {
      no_courts: 'Chưa có sân yêu thích',
      no_courts_sub: 'Thêm sân bạn hay chơi để nhận gợi ý kèo phù hợp hơn.',
      login_required: 'Đăng nhập để xem hồ sơ',
      login_required_sub: 'Quản lý thông tin cá nhân và lịch sử tham gia kèo của bạn ở một nơi gọn gàng hơn.',
      not_found: 'Không tìm thấy hồ sơ',
      not_found_sub: 'Thử tải lại hoặc đăng nhập lại để tiếp tục.',
    },
  },
  onboarding: {
    complete: 'Hoàn tất',
    next: 'Tiếp theo',
    start: 'Bắt đầu ngay',
    title: 'PHÂN LOẠI TRÌNH ĐỘ',
    step_label: 'BƯỚC',
    result_title: 'KẾT QUẢ TỰ ĐÁNH GIÁ',
    initial_elo: 'Elo khởi điểm dự kiến',
    redo_quiz: 'LÀM LẠI QUIZ',
    view_result: 'Xem kết quả',
    confirm_level: 'XÁC NHẬN MỨC NÀY',
    submit_error: 'Không thể lưu kết quả lúc này. Vui lòng thử lại sau ít phút.',
  },
  auth: {
    login_title: 'Đăng nhập',
    otp_title: 'Xác thực OTP',
    phone_sub: 'Sử dụng số điện thoại để tiếp tục',
    otp_sub: 'Mã đã gửi tới',
    phone_placeholder: 'Nhập số điện thoại',
    phone_hint: 'Chúng tôi sẽ gửi một mã xác thực 6 số qua SMS để bảo mật tài khoản của bạn.',
    resend_otp: 'Gửi lại mã xác thực',
    change_phone: 'Đổi số điện thoại',
    submit_phone: 'Tiếp tục →',
    submit_otp: 'Xác nhận',
    processing: 'Đang xử lý...',
    trust_title: 'Bảo mật tuyệt đối',
    trust_sub: 'Thông tin của bạn được mã hóa và bảo mật theo tiêu chuẩn cao nhất.',
    no_account: 'Chưa có tài khoản?',
    join_now: 'Tham gia ngay',
  },
  session_detail: {
    title: 'CHI TIẾT KÈO',
    status: {
      updated: 'Đã cập nhật thông tin kèo',
    },
    meta: {
      time: 'Thời gian',
      cost: 'Chi phí',
      notes: 'Ghi chú',
    },
    result: {
      team_a: 'Đội A',
      team_b: 'Đội B',
      confirm_title: 'Xác nhận kết quả',
      win: 'THẮNG',
      loss: 'THUA',
      draw: 'HÒA',
      dispute_title: 'Khiếu nại kết quả',
      dispute_placeholder: 'Nhập lý do khiếu nại...',
      dispute_content: 'Nội dung khiếu nại',
      dispute_action: 'Khiếu nại',
      confirm_action: 'Xác nhận',
      share: 'Chia sẻ',
      status: {
        confirmed: 'Bạn đã xác nhận kết quả',
        disputed: 'Bạn đã khiếu nại kết quả',
      },
    },
    elo_banner: {
      title: 'KÈO TÍNH ĐIỂM ELO',
      description: 'Kết quả trận đấu này sẽ ảnh hưởng đến trình độ (Elo) của bạn.',
    },
    errors: {
      load_failed: 'Không thể tải thông tin kèo',
      not_found: 'Không tìm thấy thông tin kèo hoặc kèo đã bị xóa.',
      share_failed: 'Không thể chia sẻ kèo',
    },
  },
  session_join: {
    dialogs: {
      login_required: {
        title: 'Yêu cầu đăng nhập',
        message: 'Bạn cần đăng nhập để tham gia kèo này.',
      },
      login_required_request: 'Bạn cần đăng nhập để gửi yêu cầu tham gia.',
      deadline_passed: {
        title: 'Hết hạn đăng ký',
        message: 'Thời gian đăng ký tham gia kèo này đã kết thúc.',
      },
      join_failed: {
        title: 'Tham gia thất bại',
      },
      join_success: {
        title: 'Tham gia thành công',
        message: 'Chào mừng bạn đến với kèo! Hãy chuẩn bị sẵn sàng nhé.',
      },
      request_failed: {
        title: 'Gửi yêu cầu thất bại',
      },
      request_success: {
        title: 'Đã gửi yêu cầu',
        message: 'Yêu cầu của bạn đã được gửi tới host. Vui lòng chờ phản hồi nhé.',
      },
      waitlist_success: {
        title: 'Đã đăng ký dự bị',
        message: 'Bạn đã được thêm vào danh sách dự bị. Chúng tôi sẽ báo nếu có chỗ trống!',
      },
      leave_session: {
        title: 'Rời kèo',
        message: 'Bạn có chắc chắn muốn rời khỏi kèo này không?',
        confirm: 'Rời kèo',
      },
      leave_failed: {
        title: 'Rời kèo thất bại',
      },
      cancel_session: {
        title: 'Hủy kèo',
        message: 'Bạn là host. Việc hủy kèo sẽ thông báo tới tất cả thành viên. Bạn chắc chứ?',
        confirm: 'Hủy kèo',
      },
      cancel_failed: {
        title: 'Hủy kèo thất bại',
      },
      cancel_request: {
        title: 'Hủy yêu cầu',
        message: 'Bạn có muốn hủy yêu cầu tham gia kèo này không?',
        confirm: 'Hủy yêu cầu',
      },
    },
    button: {
      waiting_host: 'Đang chờ host phản hồi',
      waiting_host_sub: 'Yêu cầu tham gia của bạn đã được gửi. Host sẽ xem và phản hồi sớm.',
      recent_message: 'Tin nhắn gần nhất',
      cancel_request: 'Hủy yêu cầu tham gia',
      rejected: 'Yêu cầu trước đó đã bị từ chối',
      host_feedback: 'Phản hồi từ host',
      join_now: 'Tham gia ngay',
      register_waitlist: 'Đăng ký dự bị',
      request_join: 'Xin vào kèo',
    },
    errors: {
      cancel_request_failed: 'Không thể hủy yêu cầu: ',
    },
  },
  join_modal: {
    request: {
      eyebrow: 'YÊU CẦU THAM GIA',
      title: 'XIN VÀO KÈO',
      description: 'Kèo này cần sự đồng ý của host. Hãy gửi lời chào và chờ host xác nhận nhé!',
      submit: 'Gửi yêu cầu',
    },
    waitlist: {
      eyebrow: 'DANH SÁCH DỰ BỊ',
      title: 'ĐĂNG KÝ DỰ BỊ',
      description: 'Kèo hiện đã đầy. Bạn có thể đăng ký dự bị để được ưu tiên nếu có thành viên rời kèo.',
      submit: 'Đăng ký dự bị',
    },
    skill_warning: {
      title: 'CHÊNH LỆCH TRÌNH ĐỘ',
      description: 'Trình độ của bạn thấp hơn yêu cầu của kèo này. Host có quyền từ chối nếu muốn đảm bảo chất lượng trận đấu.',
    },
    intro: {
      title: 'LỜI CHÀO (TÙY CHỌN)',
      description: 'Hãy giới thiệu ngắn gọn về bản thân để host tin tưởng hơn nhé.',
      placeholder_request: 'Chào host, mình muốn tham gia kèo này...',
      placeholder_waitlist: 'Mình muốn đăng ký dự bị, nếu có slot báo mình nhé!',
    },
    privacy: {
      title: 'QUYỀN RIÊNG TƯ',
      description: 'Thông tin liên hệ (số điện thoại) của bạn sẽ chỉ hiển thị với thành viên trong kèo sau khi bạn được chấp nhận.',
    },
  },
} as const
