export const STRINGS = {
  common: {
    confirmed: 'Đã xác nhận',
    pending: 'Đang chờ',
    cancelled: 'Đã hủy',
    loading: 'Đang tải...',
    error: 'Đã có lỗi xảy ra',
    retry: 'Thử lại',
    close: 'Đóng',
    back: 'Quay lại',
    save: 'Lưu',
    edit: 'Sửa',
    delete: 'Xóa',
    confirm: 'Xác nhận',
    share: 'Chia sẻ',
  },
  session: {
    status: {
      open: 'Đang mở',
      full: 'Đã đầy',
      starting_soon: 'Sắp bắt đầu',
      past: 'Đã kết thúc',
      cancelled: 'Đã hủy',
      in_progress: 'Đang diễn ra',
    },
    booking: {
      confirmed: 'Đã đặt sân',
      unconfirmed: 'Chưa đặt sân',
      waiting: 'Chờ đặt sân',
    },
    roles: {
      host: 'Chủ kèo',
      player: 'Thành viên',
    },
    actions: {
      join: 'Vào kèo',
      leave: 'Rời kèo',
      cancel_request: 'Hủy yêu cầu',
      review_requests: 'Duyệt yêu cầu',
      edit_session: 'Sửa kèo',
      report_result: 'Báo kết quả',
      confirm_result: 'Xác nhận kết quả',
    },
  },
  home: {
    greeting: {
      morning: 'Chào buổi sáng',
      afternoon: 'Chào buổi chiều',
      evening: 'Chào buổi tối',
      default: 'Xin chào',
    },
    prompts: {
      ready: 'Đã sẵn sàng ra sân chưa?',
      join_today: 'Hôm nay ra sân chứ?',
    },
    sections: {
      streak: 'CHUỖI RA SÂN',
      personalized: 'Dành riêng cho bạn',
      personalized_sub: 'Gợi ý hợp gu',
      rescue: 'Cứu nét khẩn cấp',
      rescue_sub: 'Cần người gấp',
      familiar_courts: 'Sân quen của bạn',
      familiar_courts_sub: 'Sân quen',
      upcoming: 'Trận của bạn',
      upcoming_sub: 'Sắp diễn ra',
    },
    actions: {
      create_session: 'Tạo kèo mới',
      view_session: 'XEM KÈO',
      join_session: 'VÀO KÈO',
      prioritize_match: 'ƯU TIÊN GHÉP',
      ready: 'Sẵn sàng',
    },
  },
  find_session: {
    title: 'TÌM KÈO',
    search_placeholder: 'Tìm theo tên sân, địa chỉ...',
    filters: {
      title: 'Bộ lọc',
      skill_level: 'Trình độ',
      date: 'Ngày chơi',
      court: 'Sân đấu',
      reset: 'Thiết lập lại',
      apply: 'Áp dụng',
    },
    empty: {
      no_results: 'Không tìm thấy kèo nào',
      no_results_sub: 'Thử thay đổi bộ lọc hoặc khu vực tìm kiếm khác xem sao nhé.',
    },
  },
  profile: {
    title: 'HỒ SƠ',
    sections: {
      overview: 'TỔNG QUAN',
      community: 'CỘNG ĐỒNG',
      achievements: 'DANH HIỆU',
      courts: 'SÂN QUEN',
      history: 'LỊCH SỬ',
      account: 'TÀI KHOẢN',
      settings: 'CÀI ĐẶT',
    },
    stats: {
      matches: 'Trận đấu',
      hosted: 'Đã host',
      reliability: 'Độ tin cậy',
      joined_year: 'Thành viên từ',
    },
    actions: {
      edit: 'Sửa hồ sơ',
      logout: 'Đăng xuất',
      save_changes: 'Lưu thay đổi',
      cancel_changes: 'Hủy thay đổi',
    },
  },
  onboarding: {
    complete: 'Hoàn tất',
    next: 'Tiếp theo',
    start: 'Bắt đầu ngay',
  },
} as const
